@API_HostAddress=http://localhost:5294/api/courses

# List Courses
GET {{API_HostAddress}}
Accept: application/json
Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18ydG9xUHlBZDg1M0FZNWM3dkRXU25mbm9xUHYiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3NDIxMzY0NjYsImZ2YSI6WzY4NjIsLTFdLCJpYXQiOjE3NDIxMzY0MDYsImlzcyI6Imh0dHBzOi8vY2xlYXItbGlvbi04Ni5jbGVyay5hY2NvdW50cy5kZXYiLCJuYmYiOjE3NDIxMzYzOTYsInNpZCI6InNlc3NfMnVCYXcyR09nMUVJazROM1pWcmk4UnpsZnhjIiwic3ViIjoidXNlcl8ydG9zMWZoOFhFOHN2R1VBSVMxNnJqU2d3RkcifQ.ceRu2FsIW8XVFqkg5TPzde-65080I8Jjnkds_GLYvhjYjiySBpZIx7r51vTQnlel320RaCabpAkgonyxFAeDx4zSME32KLRUmv08NJb4LYUzYO3-1Ad0HVlzicNB91xaFAx1BF_3mBgRbe3hnYg04zHOaoDQCCMAdvk8XQN0qtXRYl8o5t7MoZ1kS4TrUko9A363SooeXcjIux_1n6aCCq3-Q7_9hq6BmONyMofuXIn7rQaOn6czaNcH93lolNAhbWZTz9CVpz38H4ThuyfCx9e0elCSi8OSytBZURK6exMFsadrNQ0TDqUtedCMyUtZy9reKOspE23wG7KC6ZIzlw

###


# Get Course
GET {{API_HostAddress}}/a71bd3ae-11d7-43dd-ac2d-0043433774db
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18ydG9xUHlBZDg1M0FZNWM3dkRXU25mbm9xUHYiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3NDIxMzk4NDksImZ2YSI6WzY5MTgsLTFdLCJpYXQiOjE3NDIxMzk3ODksImlzcyI6Imh0dHBzOi8vY2xlYXItbGlvbi04Ni5jbGVyay5hY2NvdW50cy5kZXYiLCJuYmYiOjE3NDIxMzk3NzksInNpZCI6InNlc3NfMnVCYXcyR09nMUVJazROM1pWcmk4UnpsZnhjIiwic3ViIjoidXNlcl8ydG9zMWZoOFhFOHN2R1VBSVMxNnJqU2d3RkcifQ.Vn6mR6mumuoCl1FStlNrksuPQRBpHgfEpckTDnKj94rVpNuTpim22Bs8JOdI1EKOg298jYqT3V2shHUUaDhP3wa0aSS-DcpzB0D2x7iVxSU82-GR4b-GzX1sn0Qa7XLYqi7_0c17wd9JCUEdgeL-im766sxJUkhdtVRklLA_b6m4k__RUZLE123LydJFfzFlM5Ez_cezXZnOUTeT_nvtj5vGlYrRMBmjF1lNutKu4bAq5GQYLsJ3NgyedB30HGomcqenJmaVlmo55qcM4qznJdWJy4Hpzu4c1_A6FAGRUQgx3HXNnqEgWQ8MlfkQP7WM4HAE_lWhNkN7uHK6zq4tBQ

###

# Create Course
POST {{API_HostAddress}}
Accept: application/json
Content-Type: application/json

{
  "userId": "user_2tXC8dO5dNaarhBy0OYrCjIDRbF",
  "title": "Course 1"
}
###

# Add new Chapter to a Course
POST {{API_HostAddress}}/731d69ad-bff0-4c53-9f4c-dd43037270ac/chapters
Accept: application/json
Content-Type: application/json

{
  "title": "Chapter 2"
}
###

# Reorder Chapters
PUT {{API_HostAddress}}/a71bd3ae-11d7-43dd-ac2d-0043433774db/chapters
Accept: application/json
Content-Type: application/json

{
  "chapterIdList": [
    "7ec6656f-88c9-4f4e-a7fd-112eb2747a3e",
    "28b061da-9943-4721-81d0-e201a0c810a9",
    "56596ab7-3190-40a6-8ddc-e0f95be9339e"
  ]
}
###




# Delete Course
DELETE {{API_HostAddress}}/c1a716b8-51ce-4134-804f-6ba77ce7f497
Accept: application/json
Content-Type: application/json

###

# Modify Course
PATCH {{API_HostAddress}}/731d69ad-bff0-4c53-9f4c-dd43037270ac
Accept: application/json
Content-Type: application/json

{
  "title": "Course 1 - modified"
}
###
