@API_HostAddress=http://localhost:5294/api/courses

# List Courses
GET {{API_HostAddress}}
Accept: application/json
Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18ydG9xUHlBZDg1M0FZNWM3dkRXU25mbm9xUHYiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3NDIxMzY0NjYsImZ2YSI6WzY4NjIsLTFdLCJpYXQiOjE3NDIxMzY0MDYsImlzcyI6Imh0dHBzOi8vY2xlYXItbGlvbi04Ni5jbGVyay5hY2NvdW50cy5kZXYiLCJuYmYiOjE3NDIxMzYzOTYsInNpZCI6InNlc3NfMnVCYXcyR09nMUVJazROM1pWcmk4UnpsZnhjIiwic3ViIjoidXNlcl8ydG9zMWZoOFhFOHN2R1VBSVMxNnJqU2d3RkcifQ.ceRu2FsIW8XVFqkg5TPzde-65080I8Jjnkds_GLYvhjYjiySBpZIx7r51vTQnlel320RaCabpAkgonyxFAeDx4zSME32KLRUmv08NJb4LYUzYO3-1Ad0HVlzicNB91xaFAx1BF_3mBgRbe3hnYg04zHOaoDQCCMAdvk8XQN0qtXRYl8o5t7MoZ1kS4TrUko9A363SooeXcjIux_1n6aCCq3-Q7_9hq6BmONyMofuXIn7rQaOn6czaNcH93lolNAhbWZTz9CVpz38H4ThuyfCx9e0elCSi8OSytBZURK6exMFsadrNQ0TDqUtedCMyUtZy9reKOspE23wG7KC6ZIzlw

###

# List Owned Courses
GET {{API_HostAddress}}/teacher
Accept: application/json
Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18ydG9xUHlBZDg1M0FZNWM3dkRXU25mbm9xUHYiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3NDIxMzY0NjYsImZ2YSI6WzY4NjIsLTFdLCJpYXQiOjE3NDIxMzY0MDYsImlzcyI6Imh0dHBzOi8vY2xlYXItbGlvbi04Ni5jbGVyay5hY2NvdW50cy5kZXYiLCJuYmYiOjE3NDIxMzYzOTYsInNpZCI6InNlc3NfMnVCYXcyR09nMUVJazROM1pWcmk4UnpsZnhjIiwic3ViIjoidXNlcl8ydG9zMWZoOFhFOHN2R1VBSVMxNnJqU2d3RkcifQ.ceRu2FsIW8XVFqkg5TPzde-65080I8Jjnkds_GLYvhjYjiySBpZIx7r51vTQnlel320RaCabpAkgonyxFAeDx4zSME32KLRUmv08NJb4LYUzYO3-1Ad0HVlzicNB91xaFAx1BF_3mBgRbe3hnYg04zHOaoDQCCMAdvk8XQN0qtXRYl8o5t7MoZ1kS4TrUko9A363SooeXcjIux_1n6aCCq3-Q7_9hq6BmONyMofuXIn7rQaOn6czaNcH93lolNAhbWZTz9CVpz38H4ThuyfCx9e0elCSi8OSytBZURK6exMFsadrNQ0TDqUtedCMyUtZy9reKOspE23wG7KC6ZIzlw

###



# Get Course
GET {{API_HostAddress}}/a71bd3ae-11d7-43dd-ac2d-0043433774dc
Accept: application/json
Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18ydG9xUHlBZDg1M0FZNWM3dkRXU25mbm9xUHYiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3NDIxNDE2MjksImZ2YSI6WzY5NDgsLTFdLCJpYXQiOjE3NDIxNDE1NjksImlzcyI6Imh0dHBzOi8vY2xlYXItbGlvbi04Ni5jbGVyay5hY2NvdW50cy5kZXYiLCJuYmYiOjE3NDIxNDE1NTksInNpZCI6InNlc3NfMnVCYXcyR09nMUVJazROM1pWcmk4UnpsZnhjIiwic3ViIjoidXNlcl8ydG9zMWZoOFhFOHN2R1VBSVMxNnJqU2d3RkcifQ.gTLVFkIYBProO6j4Y8vpch_AWlTdgII21dgqckPeL2OVrWVwsEfsba4Ob2rEHnAhYnH_SoczmWt7Fe56WJbbwb9WsRjGrzBSpNaHYe0Xm3t9iV2sv3_a5vIlCqM6gZ2YvYa4GfztF40C5c9L-PfVVPX3ankfj0DTzOLZ4l0oWYBXIVRs3ja8iUA2G3syIKBKYESn0EKKm1dt76z-2y9did_diohkEd5WtoGfxvYIWz4prrb0dnwyh7JKfRY_S9jjBYSdDQ3Q_aYckMCgbcoiL_YMbbsbQkABLePBeaGybUbsuSxmIyq5H8d8nDfljBypMXX_dlxlL2Xtut8gOypHL

###

# Create Course
POST {{API_HostAddress}}
Accept: application/json
Content-Type: application/json

{
  "userId": "user_2tXC8dO5dNaarhBy0OYrCjIDRbF",
  "title": "Course 1"
}
###

# Add new Chapter to a Course
POST {{API_HostAddress}}/731d69ad-bff0-4c53-9f4c-dd43037270ac/chapters
Accept: application/json
Content-Type: application/json

{
  "title": "Chapter 2"
}
###

# Reorder Chapters
PUT {{API_HostAddress}}/a71bd3ae-11d7-43dd-ac2d-0043433774db/chapters
Accept: application/json
Content-Type: application/json

{
  "chapterIdList": [
    "7ec6656f-88c9-4f4e-a7fd-112eb2747a3e",
    "28b061da-9943-4721-81d0-e201a0c810a9",
    "56596ab7-3190-40a6-8ddc-e0f95be9339e"
  ]
}
###




# Delete Course
DELETE {{API_HostAddress}}/c1a716b8-51ce-4134-804f-6ba77ce7f497
Accept: application/json
Content-Type: application/json

###

# Modify Course
PATCH {{API_HostAddress}}/731d69ad-bff0-4c53-9f4c-dd43037270ac
Accept: application/json
Content-Type: application/json

{
  "title": "Course 1 - modified"
}
###
