@API_HostAddress=http://localhost:5294/api/payment

# Checkout a Course
POST {{API_HostAddress}}/bdd1fcd4-d857-4870-bea9-78e7146a450d/checkout
Accept: application/json
Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18ydG9xUHlBZDg1M0FZNWM3dkRXU25mbm9xUHYiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3NDIxNDE2MjksImZ2YSI6WzY5NDgsLTFdLCJpYXQiOjE3NDIxNDE1NjksImlzcyI6Imh0dHBzOi8vY2xlYXItbGlvbi04Ni5jbGVyay5hY2NvdW50cy5kZXYiLCJuYmYiOjE3NDIxNDE1NTksInNpZCI6InNlc3NfMnVCYXcyR09nMUVJazROM1pWcmk4UnpsZnhjIiwic3ViIjoidXNlcl8ydG9zMWZoOFhFOHN2R1VBSVMxNnJqU2d3RkcifQ.gTLVFkIYBProO6j4Y8vpch_AWlTdgII21dgqckPeL2OVrWVwsEfsba4Ob2rEHnAhYnH_SoczmWt7Fe56WJbbwb9WsRjGrzBSpNaHYe0Xm3t9iV2sv3_a5vIlCqM6gZ2YvYa4GfztF40C5c9L-PfVVPX3ankfj0DTzOLZ4l0oWYBXIVRs3ja8iUA2G3syIKBKYESn0EKKm1dt76z-2y9did_diohkEd5WtoGfxvYIWz4prrb0dnwyh7JKfRY_S9jjBYSdDQ3Q_aYckMCgbcoiL_YMbbsbQkABLePBeaGybUbsuSxmIyq5H8d8nDfljBypMXX_dlxlL2Xtut8gOypHL

###


# Webhook
POST {{API_HostAddress}}/webhook
Accept: application/json
Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18ydG9xUHlBZDg1M0FZNWM3dkRXU25mbm9xUHYiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3NDIxNDE2MjksImZ2YSI6WzY5NDgsLTFdLCJpYXQiOjE3NDIxNDE1NjksImlzcyI6Imh0dHBzOi8vY2xlYXItbGlvbi04Ni5jbGVyay5hY2NvdW50cy5kZXYiLCJuYmYiOjE3NDIxNDE1NTksInNpZCI6InNlc3NfMnVCYXcyR09nMUVJazROM1pWcmk4UnpsZnhjIiwic3ViIjoidXNlcl8ydG9zMWZoOFhFOHN2R1VBSVMxNnJqU2d3RkcifQ.gTLVFkIYBProO6j4Y8vpch_AWlTdgII21dgqckPeL2OVrWVwsEfsba4Ob2rEHnAhYnH_SoczmWt7Fe56WJbbwb9WsRjGrzBSpNaHYe0Xm3t9iV2sv3_a5vIlCqM6gZ2YvYa4GfztF40C5c9L-PfVVPX3ankfj0DTzOLZ4l0oWYBXIVRs3ja8iUA2G3syIKBKYESn0EKKm1dt76z-2y9did_diohkEd5WtoGfxvYIWz4prrb0dnwyh7JKfRY_S9jjBYSdDQ3Q_aYckMCgbcoiL_YMbbsbQkABLePBeaGybUbsuSxmIyq5H8d8nDfljBypMXX_dlxlL2Xtut8gOypHL

###
